{
  "hash": "5861604ddafc15a8cedcc4d8e0c812d7",
  "result": {
    "markdown": "---\ntitle: \"Analysis tools and QC\"\nproject:\n  execute-dir: project\n---\n\n\n::: {.callout-note}\n## Learning outcomes\n\n**After having completed this chapter you will be able to:**\n\n- Load single cell data into R\n- Explain the basic structure of a `Seurat` object and extract count data and metadata\n- Calculate and visualize quality measures based on:\n    - mitochondrial genes\n    - ribosomal genes\n    - hemoglobin genes\n    - relative gene expression\n- Interpret the above quality measures per cell.\n- Perform cell filtering based on quality thresholds\n:::\n\n## Material\n\n\n{{< downloadthis ../assets/pdf/04_analysis_tools_qc.pdf dname=\"04_analysis_tools_qc\" label=\"Download the presentation\" icon=\"filetype-pdf\" >}}\n\n\n{{< video https://youtu.be/YT7xeHVnTw4?si=YkNt4QOpgqMrLulb >}}\n\n\n\n## Exercises\n\n### Loading scRNAseq data\n\nThe next step after the generation of the count matrices with `cellranger count`, is the data analysis. The `R` package `Seurat` is currently the most popular software to do this. To start working with `Seurat` you can load it into your environment like this:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-1_eedb21620a983631c3c7251a44d204d5'}\n\n```{.r .cell-code}\nlibrary(Seurat)\n```\n:::\n\n\n::: {.callout-tip}\n## Tip: make an R script\nYou could type and copy-paste the commands of these exercises directly in the console. However, that makes it hard to track what you have done. In addition, it can be nice to add comments to your code, so you can read back why you have made certain choices. In order to do that, do not write commands in the console, but write them in a script, and send them to the console with <kbd>^ Ctrl + ⏎ Enter</kbd> (Windows) or <kbd>⌘ Command + ⏎ Enter</kbd> (MacOS).\n:::\n\nFirst, we will load a file specifying the different samples, and create an object specifying the location of the count data:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-2_2f32338b9b0f8dcd2a90ca1af2b191b3'}\n\n```{.r .cell-code}\nsample_info <- read.csv(\"course_data/sample_info_course.csv\")\ndatadirs <- file.path(\"course_data\", \"count_matrices\", sample_info$SampleName,\n                      \"outs\", \"filtered_feature_bc_matrix\")\nnames(datadirs) <- gsub(\"_\", \"-\", sample_info$SampleName)\ndatadirs <- datadirs[1:3]\n```\n:::\n\n\nThe object `datadirs` is a named vector specifying the paths of the count directories for each sample:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-3_efe3c65ff12ab065d442b7e506f981e3'}\n::: {.cell-output .cell-output-stdout}\n```\n                                                             PBMMC-1 \n\"course_data/count_matrices/PBMMC_1/outs/filtered_feature_bc_matrix\" \n                                                             PBMMC-2 \n\"course_data/count_matrices/PBMMC_2/outs/filtered_feature_bc_matrix\" \n                                                             PBMMC-3 \n\"course_data/count_matrices/PBMMC_3/outs/filtered_feature_bc_matrix\" \n```\n:::\n:::\n\n\nTo run through a typical `Seurat` analysis, we will use the files that are in the directory `data/filtered_feature_bc_matrix`. This directory is part of the output generated by [`cellranger`](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger). To load this data into R and generate a sparse matrix, run the following command:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-4_02d727833be7f8129de76f4207acd36e'}\n\n```{.r .cell-code}\nsparse_matrix <- Seurat::Read10X(data.dir = datadirs)\n```\n:::\n\n\nThis imports a raw count matrix. Have a look at the counts of the first 30 cells of three genes by running:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-5_ac59dbd074c14b7529244c16f7091a1d'}\n\n```{.r .cell-code}\nsparse_matrix[c(\"PECAM1\", \"CD8A\", \"TSPAN1\"), 1:30]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3 x 30 sparse Matrix of class \"dgCMatrix\"\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n  [[ suppressing 30 column names 'PBMMC-1_AAACCTGCAGACGCAA-1', 'PBMMC-1_AAACCTGTCATCACCC-1', 'PBMMC-1_AAAGATGCATAAAGGT-1' ... ]]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                                  \nPECAM1 . . . . . . . 1 . . . . 1 . . 1 . . . . . . . 1 . . . . . .\nCD8A   . 1 . . 1 . . . . . . . . . . . . . . . . . . . . . . . . .\nTSPAN1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n```\n:::\n:::\n\n\nYou will see many dots (zeros) and a few integers representing the counts per gene per cell. \n\nTo generate a `Seurat` object, we will run `CreateSeuratObject`. Note that while creating the object, we already do some mild filtering; we only import genes that are expressed in at least 3 cells, and we only import cells that have at least 100 different genes expressed:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-6_c3155bd7e138df5a6330df5d410f3a5b'}\n\n```{.r .cell-code}\nseu <- Seurat::CreateSeuratObject(counts = sparse_matrix,\n                                  project = \"pbmmc\",\n                                  min.cells = 3,\n                                  min.features = 100)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Feature names cannot have underscores ('_'), replacing with dashes\n('-')\n```\n:::\n:::\n\n\n::: {.callout-note} \n## Function notation with `::`\nHere, we define the function together with its associated package. We do that by the syntax `package::function`. Of course, you can also call `library(package)`, and only type the function name. Since we use many different packages in this course, it can be confusing which function comes from which package. Therefore, we chose to always associate the package with the called function.\n::: \n\n::: {.callout-important}\n## Exercise\ncheck what's in the `seu` object, by typing `seu` in the R console. How many features are in there? And how many cells?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\nTyping `seu` should return:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-7_6c52928692cb62236e45400234835a86'}\n::: {.cell-output .cell-output-stdout}\n```\nAn object of class Seurat \n18673 features across 6946 samples within 1 assay \nActive assay: RNA (18673 features, 0 variable features)\n 1 layer present: counts\n```\n:::\n:::\n\n\nThis means that we have 18673 genes (features) in there, and 6946 cells (samples)\n\n:::     \n\n### The `Seurat` object\n\nThe `seu` object we have created has the class `Seurat`. The object contains multi-level slots and lists. Each `Seurat` object contains exactly the same slots that are specified in the image below (get slot descriptions by typing `?SeuratObject::Seurat`). You can get the information inside a slot with `@`, in the same way as you would use the `$` for lists (e.g. `seu@meta.data` will return the a data frame with information on each cell). Slots can be filled with other R objects, like lists, vectors, data frames or any other class. Here's an overview of all slots that are in a `Seurat` object:\n\n![](../assets/images/seurat_object.png)\n\nIn addition to the original count table, the `Seurat` object can therefore store a lot of information that is generated during your analysis, like results of a normalization (`@assays$RNA@data`) a PCA or UMAP (`@reductions`) and the clustering (`@graphs`). It also tracks all the commands that have been used to generate the object in its current state (`@commands`). Therefore, while going through the analysis steps, the same object gets more and more of its slots filled. Because most `Seurat` functions return the input object + adjusted slots, we can use this syntax:\n\n```\nseurat_object <- Seurat::function(seurat_object)\n```\n\nSo, the function takes an object as input and we assign it to an object with the same name. Meaning that we overwrite the object used as input. This is fine in many cases, because `Seurat` adds information to the input object, and returns is. We will use this syntax for the first time at [Normalization and scaling](day1-3_normalization_scaling.qmd).\n\n::: {.callout-note}\n## Getting specific information out of the `Seurat` object\nIn order to get specific data you can use the `@` and `$` symbols to browse through the objects. However, `Seurat` comes with a lot of convenience functions, that are easier to use. So, e.g. to get the raw count matrix, you could type `seu@assays$RNA@layers$counts`, however, this is equivalent to `GetAssayData(object = seu, layer = \"counts\")`. More information on these convenience functions [here](https://satijalab.org/seurat/articles/essential_commands.html).\n::: \n\n::: {.callout-important}\n## Exercise\nA. Have a look at the `seu` object by running `View(seu)`. What is in there? What is stored in `@active.ident`? \n\nB. Have a look at the `data.frame` stored at `seu@meta.data` what kind of information is in there?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n### Answer A\n\nThere are many slots as described in the above figure. The slot `@active.ident` contains data specifying the samples, e.g. `table(seu@active.ident)` returns:\n\n```\nPBMMC-1 PBMMC-2 PBMMC-3 \n1612    3105    2229 \n```\n\nWhich are the number of cells per sample. \n\n### Answer B\nRunning `head(seu@meta.data)` returns:\n\n```\n                            orig.ident nCount_RNA nFeature_RNA\nPBMMC-1_AAACCTGCAGACGCAA-1    PBMMC-1       2401          909\nPBMMC-1_AAACCTGTCATCACCC-1    PBMMC-1       3532          760\nPBMMC-1_AAAGATGCATAAAGGT-1    PBMMC-1       3972         1215\nPBMMC-1_AAAGCAAAGCAGCGTA-1    PBMMC-1       3569          894\nPBMMC-1_AAAGCAACAATAACGA-1    PBMMC-1       2982          730\nPBMMC-1_AAAGCAACATCAGTCA-1    PBMMC-1      22284         3108\n```\n\nGiving you the names of three columns and a row for each cell:\n\n* `orig_ident`: the original identity (origin) of a cell.\n* `nCount_RNA`: the number of reads assigned to a cell.\n* `nFeature_RNA`: the number of expressed features (genes) per cell.\n::: \n\nLuckily, usually you do not have to dive into this structure to retrieve information. For example, information in the slot `@meta.data` can be retrieved and set by using `$` or `[[]]`.\n\n::: {.callout-note}\nThere is a subtle difference here between `$` and `[[]]`. While `$` returns a vector of the column in `@meta.data`, `[[]]` returns a `data.frame`.\n:::\n\n::: {.callout-important} \n## Exercise\nGenerate a histogram of the column `nCount_RNA` at `seu@meta.data`, with the base function `hist`.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-8_0c87da729ea48572ce16c7bce1d05820'}\n\n```{.r .cell-code}\nhist(seu$nCount_RNA)\n```\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nor\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-9_525270ff3f2715e84d6ea13853b74899'}\n\n```{.r .cell-code}\nhist(seu@meta.data$nCount_RNA)\n```\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n:::\n\nThere are also built-in functions to plot data from `Seurat` object, for example `FeatureScatter`. This function enables you easily draw a scatterplot from a `Seurat` object:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-10_04ad5bb632214995dc6e2ab4eb81b624'}\n\n```{.r .cell-code}\nSeurat::FeatureScatter(seu, feature1 = \"nCount_RNA\", feature2 = \"nFeature_RNA\")\n```\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nYou can find a nice overview of such functions [here](https://satijalab.org/seurat/articles/essential_commands.html). \n\n\n### Visualizing QC per cell and gene\n\nWhile generating the `Seurat` object, there were already some quality measures calculated for each cell, namely the total UMI counts per cell (`nCount_RNA`) and the total number of detected features per cell (`nFeature_RNA`). We can plot those in a violin plot and evaluate their distribution per sample:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-11_3397057f58be396cc57cd870d068038f'}\n\n```{.r .cell-code}\nSeurat::VlnPlot(seu, features = c(\"nCount_RNA\",\n                                  \"nFeature_RNA\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Default search for \"data\" layer in \"RNA\" assay yielded no results;\nutilizing \"counts\" layer instead.\n```\n:::\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nYou can see that there is quite a wide range for both. A cell with low number of detected features or counts might not give you a lot of information, while a high number of detected features/counts might point to doublets.\n\nSingle cells have often undergone sampling and/or dissociation and/or sorting. Therefore, there are often cells and genes in your dataset that cause variation due to technical reasons. In the following steps, we will visualize those and make decisions on whether or not to remove cells or genes with extreme values.\n\nWe will start with calculating the percentage of counts coming from transcript types:\n\n- **Mitochondrial genes**: If a cell membrane is damaged, it looses free RNA quicker compared to mitochondrial RNA, because the latter is part of the mitochondrion. A high relative amount of mitochondrial counts can therefore point to damaged cells ([Lun et al. 2016](https://f1000research.com/articles/5-2122)). \n- **Ribosomal genes**: Are not rRNA (ribosomal RNA) but is mRNA that code for ribosomal proteins. They do not point to specific issues, but it can be good to have a look at their relative abundance. They can have biological relevance (e.g. [Caron et al. 2020](https://www.nature.com/articles/s41598-020-64929-x)).\n- **Hemoglobin genes**: these transcripts are very abundant in erythrocytes. Depending on your application, you can expect 'contamination' of erythrocytes and select against it. \n\nIn order to have an idea about the relative counts of these type of genes in our dataset, we can calculate their expression as relative counts in each cell. We do that by selecting genes based on patterns (e.g. `^MT-` matches with all gene names starting with `MT`, i.e. mitochondrial genes):\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-12_11b77037da6a4cc2b8f65c0f33bec034'}\n\n```{.r .cell-code}\n# mitochondrial genes\nseu <- Seurat::PercentageFeatureSet(seu, \n                                    pattern = \"^MT-\", \n                                    col.name = \"percent.mito\")\n\n# ribosomal genes\nseu <- Seurat::PercentageFeatureSet(seu, \n                                    pattern = \"^RP[SL]\",\n                                    col.name = \"percent.ribo\")\n\n# hemoglobin genes (but not HBP)\nseu <- Seurat::PercentageFeatureSet(seu,\n                                    pattern = \"^HB[^(P)]\",\n                                    col.name = \"percent.globin\")\n```\n:::\n\n\n\n::: {.callout-important}\n## Exercise\nRun the commands and check out the metadata data frame at `seu@meta.data`. What has changed?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\nIf we type `head(seu@meta.data)` it returns:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-13_b9f05f66792a98c00298afea46102d95'}\n::: {.cell-output .cell-output-stdout}\n```\n                           orig.ident nCount_RNA nFeature_RNA percent.mito\nPBMMC-1_AAACCTGCAGACGCAA-1    PBMMC-1       2401          909     2.540608\nPBMMC-1_AAACCTGTCATCACCC-1    PBMMC-1       3532          760     5.181200\nPBMMC-1_AAAGATGCATAAAGGT-1    PBMMC-1       3972         1215     4.934542\nPBMMC-1_AAAGCAAAGCAGCGTA-1    PBMMC-1       3569          894     3.250210\nPBMMC-1_AAAGCAACAATAACGA-1    PBMMC-1       2982          730     3.688799\nPBMMC-1_AAAGCAACATCAGTCA-1    PBMMC-1      22284         3108     3.181655\n                           percent.ribo percent.globin\nPBMMC-1_AAACCTGCAGACGCAA-1     28.65473      0.1665973\nPBMMC-1_AAACCTGTCATCACCC-1     55.03964      0.1981880\nPBMMC-1_AAAGATGCATAAAGGT-1     30.43807      0.3776435\nPBMMC-1_AAAGCAAAGCAGCGTA-1     55.02942      0.3642477\nPBMMC-1_AAAGCAACAATAACGA-1     54.49363      0.1006036\nPBMMC-1_AAAGCAACATCAGTCA-1     23.40693     36.9682283\n```\n:::\n:::\n\n\nSo, the function `PercentageFeatureSet` adds a column to `meta.data`, specifying the percentage of counts for the specified gene sets. \n::: \n\nNow we can plot the distribution of these percentages in a violin plot:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-14_6d45b7c95d1bd7660c5d669a7dfb7c9b'}\n\n```{.r .cell-code}\nSeurat::VlnPlot(seu, features = c(\"percent.mito\",\n                                  \"percent.ribo\",\n                                  \"percent.globin\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Default search for \"data\" layer in \"RNA\" assay yielded no results;\nutilizing \"counts\" layer instead.\n```\n:::\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nYou can see that `PBMMC-2` is quite different from the two others, it has a group of cells with very low ribosomal counts and one with very high globin counts. Maybe these two percentages are negatively correlated? Let's have a look, by plotting the two percentages against each other:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-15_b7c19110b78f92cbeeb721273940355e'}\n\n```{.r .cell-code}\nSeurat::FeatureScatter(seu, \n                       feature1 = \"percent.globin\", \n                       feature2 = \"percent.ribo\")\n```\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n::: {.callout-important}\n## Exercise\nAre they correlated? What kind of cells might have a high abundance of hemoglobin transcripts and low ribosomal transcripts? \n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\nYes there is a negative correlation. Erythrocytes (red blood cells) have a high abundance of hemoglobin transcripts and low abundance of ribosomal transcripts. These are most likely erythroid cells, i.e. the cells predecessing erythrocytes in the bone marrow. \n::: \n\nWe can also evaluate the relative expression of other genes in our dataset, for example, the ones that are most highly expressed. Some very highly expressed genes might point to a technical cause, and we might consider to remove them. Below you will find a simple function to generate a boxplot of relative counts per gene per cell. Load it into your environment and run it on our `seu` object:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-16_3da6fc33aaad679ef184b8f2b89b6b80'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(Matrix)\nlibrary(Seurat)\n\nmost_expressed_boxplot <- function(object, ngenes = 20){\n  \n  # matrix of raw counts\n  cts <- Seurat::GetAssayData(object, assay = \"RNA\", layer = \"counts\")\n  \n  # get percentage/cell\n  cts <- t(cts)/colSums(cts)*100\n  medians <- apply(cts, 2, median)\n  \n  # get top n genes\n  most_expressed <- order(medians, decreasing = T)[ngenes:1]\n  most_exp_matrix <- as.matrix((cts[,most_expressed]))\n  \n  # prepare for plotting\n  most_exp_df <- stack(as.data.frame(most_exp_matrix))\n  colnames(most_exp_df) <- c(\"perc_total\", \"gene\")\n  \n  # boxplot with ggplot2\n  boxplot <- ggplot(most_exp_df, aes(x=gene, y=perc_total)) +\n    geom_boxplot() +\n    coord_flip()\n  return(boxplot)\n}\n\nmost_expressed_boxplot(seu, 20)\n```\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nAs for most 10X based poly-A enriched single cell datasets, we find a relatively high expression of MALAT1. Many researchers choose to remove it, but it can have biological relevance (e.g. [Shaat et al. 2021](https://www.nature.com/articles/s41420-020-00383-y)). \n\n### Cell filtering\n\nBased on the QC process we went through we can come to the following conclusions:\n\n- There are no cells with very high mitochondrial gene counts.\n- There are some cells with a hemoglobin and low ribosomal counts, and these are probably erythrocytes.\n- There are some cells with a very low and very high number of features. These might point to non-informative cells and doublets respectively. \n- The 'usual suspect' MALAT1 sometimes makes up a large part of the counts per cell. As we do not see any other suggestions of dying/stressed cells, we leave it in. \n\nIn this case, a sensible decision would be to do mild filtering on the number of features per cell and mitochondrial counts. We can leave the possible erythrocytes in for now, and see where they end up later during the dimensionality reduction. \n\nIn the M&M of the [publication](https://www.nature.com/articles/s41598-020-64929-x#Sec7), the authors describe that they have used a threshold of < 8% mitochondrial counts and > 200 features per cell. To filter against possible doublets, here, we also filter out cells with > 5000 detected features/cell. Filtering `Seurat` objects can be done with the `subset` method for class `SeuratObject`:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-17_84d59b6ca6804d269251babcd1d9fe7c'}\n\n```{.r .cell-code}\nseu <- subset(seu, subset = nFeature_RNA > 200 & \n                nFeature_RNA < 5000 &\n                percent.mito < 8)\n```\n:::\n\n\nTo evaluate this did the trick we can visualize those parameters again in a violin plot:\n\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-18_db0a2d5e42b86c54ecaf6627d8057f14'}\n\n```{.r .cell-code}\nSeurat::VlnPlot(seu, features = c(\"nFeature_RNA\",\n                                  \"percent.mito\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Default search for \"data\" layer in \"RNA\" assay yielded no results;\nutilizing \"counts\" layer instead.\n```\n:::\n\n::: {.cell-output-display}\n![](day1-2_analysis_tools_qc_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='day1-2_analysis_tools_qc_cache/html/unnamed-chunk-19_2fb62d3e23c822b7c994678faa2195af'}\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}